# Generated by Django 2.0.7 on 2018-07-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_customer_locationlogs_restaurant_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
    ]
